packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.32.3~ynh1"

maintainers = [ ]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.32.3/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "f75ec14b9e2d71b13df88557b885d187ea5723e7605e623a35e42a2358c63a69"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.32.3/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "9e9f7cb0c34e921a95b96c2fdc0b458fae0960ac3ac41f59fdd4a127c4b78588"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.32.3/linux-386-filebrowser.tar.gz"
        i386.sha256 = "095aa85e514aea54da5a9f8f0f45c74ef022ea005615b273a18fd06135953ee0"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.32.3/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "6e814571be7853d4893a9d40da0bf260687caf80e3eb51275667265ec71a4e3f"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
