packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.31.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.0/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "296f870816a5553de2d9f2cfe4046f77a86e33130d0af0c92b60f96f2aedf364"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.0/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "e1087add9437dd3720d02280bf2dc13b31ee365143a0581cfbe305f7106c1148"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.0/linux-386-filebrowser.tar.gz"
        i386.sha256 = "a1c999f4a4d912909503ac9a26762c25cb58fb9590fe11c104eab3cecca8b691"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.0/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "71a4bd3498de92f4c3c4d1c9e4716b755bd54e1f41ab04875b3a905ae2b149c6"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
