packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.31.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.1/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "dee16329431450ae33138a5c28e841a235833992560611e16b9f583b2da1a6c6"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.1/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "5917529f03f88ab3128c89c330bd9eabfadc05cf4179887ff3ba04a111888e49"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.1/linux-386-filebrowser.tar.gz"
        i386.sha256 = "db9f32dfc8650496848549d43b1f84ea020d30346f56177f4b9cdae7a95408d7"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.1/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "2daa0b516ae4cae0be3e24a0829117d13a0c96b8f09e643baa6708704820df95"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
