packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.24.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.24.1/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "b99ee686e1e70b8a418ebc9551e034b71f83f583e18f231e34e0850c4084383b"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.24.1/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "55fc437267cc86bbc92d2ef2ecf50425ee5a70bac6e5573a212e3c5138967ab2"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.24.1/linux-386-filebrowser.tar.gz"
        i386.sha256 = "14070fafd17611b624a9f1f428ff0bc07cd380fad8eb33c90377fd8a3e080924"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.24.1/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "884c5ae5c91bb2ae7c871e9980f26182f9d80da8d0bf09d37af484689bfebe83"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
