packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.30.0~ynh2"

maintainers = [ ]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.30.0/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "3464726bae923bca41197d9e04f3f9da450de2f41338dd1c1a76ffc010cbc750"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.30.0/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "331ced65d50aae110fb16ade9db70b831db132baa153802ea73ee8d28175c9e1"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.30.0/linux-386-filebrowser.tar.gz"
        i386.sha256 = "938dc02aeed010765daaf721acfa11caeee4124a89208a1e1cbaa94537331e59"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.30.0/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "22e0b45bee4c2e115b5f6b9aa843f9e0a58364555b0ca1cf5dc01a7cceaa2632"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
