packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.25.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.25.0/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "287209e2d8b8cccbfe8d84b39a272e16517c4fc2e6eae6e2cedd57519d30b3b2"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.25.0/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "18563c11ed0876de75fc3b6b4bf9596b4ce2a484bf75215ffcf2d3f5662880f3"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.25.0/linux-386-filebrowser.tar.gz"
        i386.sha256 = "109260b4608650e5898f96cf25fc5e320fa47f1deed395ac1138b5e27daaf68d"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.25.0/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "63348c3ae98123afabb36ebe50990f43c54432e0502d81b94547dc41954727ab"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
