packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.31.2~ynh1"

maintainers = [ ]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.2/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "a4eb80ffa5845597dc50a53f40ca230636a7c957ba97390c659bced3bab1c8f1"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.2/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "6136f11f85d2cc0a7f4828772d389cad4d6d44f6840c036e3bae204deea147ae"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.2/linux-386-filebrowser.tar.gz"
        i386.sha256 = "dcd03962fee74fc517d05648a925acdab43611b85cf1500ded0ffb91111f16c4"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.31.2/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "6872328b14e1b96a9d195f0d90e0ad1a8356c4887dc437feca147915c862b3c5"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
