packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.32.1~ynh1"

maintainers = [ ]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.32.1/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "e2bd0f631d808a47a5c2dcab5dbb5a8ef971c9775f93cead6a01042ec2098769"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.32.1/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "d60e46689e0fe1b075cce98a7e7917b7760a403e272e2242b1b4ca57f42acd50"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.32.1/linux-386-filebrowser.tar.gz"
        i386.sha256 = "a056d8e2c6443e3ca7e541c943f3a08a703a0c6cc8458cb21c23cc922d8ca151"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.32.1/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "2ef2426ee3c671d6f33ef6a71ecf9e7c476475ca84844d1eca4b1dc04f9faa29"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
